on: [push, pull_request]
name: Continuous Integration

jobs:
  test:
    name: Test
    runs-on: ${{matrix.os.fullname}}
    env:
      PROJECT_NAME: Akihabara
    strategy:
      fail-fast: false
      matrix:
        os:
          - { prettyname: Windows, fullname: windows-latest }
          - { prettyname: Linux, fullname: ubuntu-latest }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      # FIXME: Setup will fail if you use a Python version lower than 3.9
      - name: Force Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      
      - name: Build (Native)
        run: |
          pip install numpy
          python build.py build --desktop cpu --opencv=cmake -vv
      
      - name: Build (.NET)
        run: dotnet build -c Debug ./src/Akihabara.sln
      
      - name: Test
        run: |
          cp "$pwd/src/${{env.PROJECT_NAME}}/bin/Debug/*/libmediapipe_c.so" "$pwd/src/${{env.PROJECT_NAME}}.Tests/bin/Debug/*/libmediapipe_c.so"
          dotnet test "$pwd/src/${{env.PROJECT_NAME}}.Tests" --logger "trx;LogFileName=TestResults-${{matrix.os.prettyname}}.trx"
        shell: pwsh

      # Attempt to upload results even if test fails.
      # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#always
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: TestResults-Linux
          path: ${{github.workspace}}/TestResults/TestResults-Linux.trx
